### PR TITLE
fix: use perform instead of perform_async if Redis is down

### LINKED ISSUE #57: Redis::TimeoutError in production
There are several Redis::TimeoutError in production from yesterday and today. This resulted in a HTTP 500 on our demo map today for example. I create this issue so we can keep an eye.

Log sample from the server:

```
[mapzy] [2022-03-03 10:46:10] [b005808e-1726-4169-b866-967491dde0e3] Redis::CannotConnectError (Error connecting to Redis on mapzy-redis-do-user-9020844-0.b.db.ondigitalocean.com:25061 (Redis::TimeoutError)):
[mapzy] [2022-03-03 10:46:10] [b005808e-1726-4169-b866-967491dde0e3]   
[mapzy] [2022-03-03 10:46:10] [b005808e-1726-4169-b866-967491dde0e3] app/controllers/concerns/trackable.rb:11:in `track_event'
[mapzy] [2022-03-03 10:46:10] [b005808e-1726-4169-b866-967491dde0e3] app/controllers/maps_controller.rb:7:in `block in <class:MapsController>'
[mapzy] [2022-03-03 10:46:15] I, [2022-03-03T10:46:15.582696 #1]  INFO -- : [9fcf4065-0b01-4a4f-8d32-2c29c10e99cf] Started GET "/maps/2" for 162.158.148.216 at 2022-03-03 10:46:15 +0000
[mapzy] [2022-03-03 10:46:15] I, [2022-03-03T10:46:15.583786 #1]  INFO -- : [9fcf4065-0b01-4a4f-8d32-2c29c10e99cf] Processing by MapsController#show as HTML
[mapzy] [2022-03-03 10:46:15] I, [2022-03-03T10:46:15.584230 #1]  INFO -- : [9fcf4065-0b01-4a4f-8d32-2c29c10e99cf]   Parameters: {"id"=>"2"}
[mapzy] [2022-03-03 10:46:15] I, [2022-03-03T10:46:15.601403 #1]  INFO -- : [9fcf4065-0b01-4a4f-8d32-2c29c10e99cf]   Rendered maps/show.html.erb within layouts/application (Duration: 9.5ms | Allocations: 4586)
[mapzy] [2022-03-03 10:46:15] I, [2022-03-03T10:46:15.602943 #1]  INFO -- : [9fcf4065-0b01-4a4f-8d32-2c29c10e99cf]   Rendered layout layouts/application.html.erb (Duration: 11.1ms | Allocations: 5237)
[mapzy] [2022-03-03 10:46:25] I, [2022-03-03T10:46:25.640933 #1]  INFO -- : [9fcf4065-0b01-4a4f-8d32-2c29c10e99cf] Completed 500 Internal Server Error in 10056ms (Views: 6.7ms | ActiveRecord: 7.8ms | Allocations: 6244)
[mapzy] [2022-03-03 10:46:25] F, [2022-03-03T10:46:25.641763 #1] FATAL -- : [9fcf4065-0b01-4a4f-8d32-2c29c10e99cf]   
[mapzy] [2022-03-03 10:46:25] [9fcf4065-0b01-4a4f-8d32-2c29c10e99cf] Redis::CannotConnectError (Error connecting to R
```

Log sample from Sidekiq:
```
[sidekiq] [2022-03-02 16:48:51] 2022-03-02T16:48:51.795Z pid=1 tid=1j8d ERROR: Error connecting to Redis on mapzy-redis-do-user-9020844-0.b.db.ondigitalocean.com:25061 (Redis::TimeoutError)
[sidekiq] [2022-03-02 16:48:51] 2022-03-02T16:48:51.796Z pid=1 tid=1j8d WARN: Redis::CannotConnectError: Error connecting to Redis on mapzy-redis-do-user-9020844-0.b.db.ondigitalocean.com:25061 (Redis::TimeoutError)
[sidekiq] [2022-03-02 16:48:51] 2022-03-02T16:48:51.796Z pid=1 tid=1j8d WARN: /usr/local/bundle/gems/redis-4.6.0/lib/redis/client.rb:398:in `rescue in establish_connection'
[sidekiq] [2022-03-02 16:48:51] /usr/local/bundle/gems/redis-4.6.0/lib/redis/client.rb:379:in `establish_connection`
```

### PR DESCRIPTION
**Pull request by sagzy**
This PR ensures that our app doesn't break because of Redis being down. If Redis is not available, the event is tracked synchronously, without persisting the arguments to Redis (use `perform`, instead of `perform_async`). Tested it with gitpod, by shutting Redis down.

Closes #57

### CODE REVIEW

File: app/controllers/concerns/trackable.rb [hunk 1]
```diff
@@ -8,6 +8,6 @@ def track_event(name = "", properties = {})
 
     # default if no event name is provided
     name = "Viewed #{controller_name} #{action_name}" if name.empty?
-    FuguWorker.perform_async(name, properties)
+    FuguWorker.perform_async_with_failover(name, properties)
```
Comment (shafy) [inline app/controllers/concerns/trackable.rb:11]: Cool, didn't know this method existed. Just assumed that it doesn't cause the app to throw an exception if Redis is down. Great!

**Review by shafy — APPROVED** [review]
Cool thanks!

File: app/controllers/concerns/trackable.rb (hunk 1 above)
Comment (sagzy) [reply app/controllers/concerns/trackable.rb:11]: It actually doesn't exist in sidekiq, it's a custom method that I added in FuguWorker. Maybe I should open up a PR on the sidekiq gem and propose it
